# Generated by Django 4.1 on 2022-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время заказа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата и время изменения заказа ')),
                ('discription', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('contacts', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='botlle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='photo'),
        ),
    ]
