# Generated by Django 4.1 on 2022-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_order'),
        ('core', '0004_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botlle',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='botlle',
            name='photo',
        ),
        migrations.AddField(
            model_name='botlle',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottles', to='clients.order', verbose_name='заказы'),
        ),
    ]
