# Generated by Django 4.1 on 2022-08-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_botlle_adress_remove_botlle_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottlesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
