# Generated by Django 4.1 on 2022-08-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bottlescount_bottle_bottlescount_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlescount',
            name='bottle',
        ),
        migrations.RemoveField(
            model_name='bottlescount',
            name='order',
        ),
    ]
