# Generated by Django 4.1 on 2022-08-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_order'),
        ('core', '0009_bottlescount_bottle_bottlescount_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botlle',
            name='orders',
        ),
        migrations.AlterField(
            model_name='bottlescount',
            name='bottle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bottlescounts', to='core.botlle'),
        ),
        migrations.AlterField(
            model_name='bottlescount',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bottlescounts', to='clients.order'),
        ),
        migrations.AddField(
            model_name='botlle',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottles', to='clients.order', verbose_name='заказы'),
        ),
    ]
