# Generated by Django 4.1 on 2022-08-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_order'),
        ('core', '0010_remove_botlle_orders_alter_bottlescount_bottle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlescount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottlescounts', to='clients.order'),
        ),
    ]
