# Generated by Django 4.1 on 2022-08-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_bottlescount_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlescount',
            name='bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottlescounts', to='core.botlle'),
        ),
    ]
