# Generated by Django 4.1 on 2022-08-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bottlescount_bottle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botlle',
            name='orders',
        ),
    ]
