# Generated by Django 4.1 on 2022-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_order_options_order_client_alter_order_name_and_more'),
        ('core', '0013_remove_botlle_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlle',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottles', to='clients.order', verbose_name='Заказы'),
        ),
    ]
