# Generated by Django 4.1 on 2022-08-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_order_options_order_client_alter_order_name_and_more'),
        ('core', '0014_botlle_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottlescount',
            name='bottle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottlescount', to='core.botlle'),
        ),
        migrations.AlterField(
            model_name='bottlescount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottlescount', to='clients.order'),
        ),
    ]
