# Generated by Django 4.1 on 2022-08-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_order_client'),
        ('core', '0018_remove_botlle_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlle',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='bottles', to='clients.order'),
        ),
    ]
