# Generated by Django 4.1 on 2022-08-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
    ]
